name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Go dependencies
      run: go get -v -t -d ./...

    - name: "Check: go fmt"
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            gofmt -s -l -d ./...
            echo "Please run: go fmt ./..."
            exit 1
        fi
        if [ "$(go mod tidy -v)" -qt 0 ]; then
            go mod tidy -v
            echo "Please run: go mod tidy"
            exit 1
        fi
